version: "3"

services:
  backend:
    build: .
    command: yarn start
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    working_dir: /app
  frontend:
    build: .
    command: yarn start
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000
    working_dir: /app
